### ISSUE TITLE
Working with the Workforce 3620

### ISSUE THREAD

**Issue by HReimann** [iobroker-community-adapters/ioBroker.epson_ecotank_et_2750#64]
I tested it with the Workforce 3620 the most values are displayed.

![image](https://user-images.githubusercontent.com/16271308/122284371-cc97bf00-ceed-11eb-83bd-7f16541dda50.png)

Thanks for the good work.

**Comment by o0shojo0o** [comment]
If you want we can also try to fill the missing data points.
For this we would have to check what is different in your `http://<Printer-IP>/PRESENTATION/ADVANCED/INFO_PRTINFO/TOP`.

**Comment by HReimann** [comment]
I had now some time to test.
Here are the screenshoot of the Firmware 
![image](https://user-images.githubusercontent.com/16271308/130474672-87284a23-9408-44a1-802d-b9b97072bc7f.png)
With the Edge Browser i get the following information:
[IE_Data.txt](https://github.com/o0shojo0o/ioBroker.epson_ecotank_et_2750/files/7033153/IE_Data.txt)
<fieldset class="group no-legend"><legend class="group">﻿</legend><dl class="values"><dt class="key"><span class="key">Firmware-Version&nbsp;:</span></dt><dd class="value clearfix"><div class="preserve-white-space">**CC23K3 24.08**</div></dd><dt class="key"><span class="key">Stammzertifikat-Version&nbsp;:</span></dt><dd class="value clearfix"><div class="preserve-white-space">02.02</div></dd><dt class="key"><span class="key">Seriennummer&nbsp;:</span></dt><dd class="value clearfix"><div class="preserve-white-space">SEGY164325</div></dd><dt class="key"><span class="key">Wi-Fi/Netzwerk-MAC-Adresse&nbsp;:</span></dt><dd class="value clearfix"><div class="preserve-white-space">AC:18:26::::</div></dd></dl></fieldset>

**Comment by o0shojo0o** [comment]
Then i would need the output of `http://<Printer-IP>/PRESENTATION/ADVANCED/INFO_NWINFO/TOP` again for the printer name.

**Comment by HReimann** [comment]
I get this Output for the printername 
![image](https://user-images.githubusercontent.com/16271308/130510554-ea978503-9343-4340-a3cd-d63533704ed2.png)
<dl class="values">
<dt class="key">
<span class="key">Druckername&nbsp;:</span>
</dt>
<dd class="value clearfix"><div class="preserve-white-space">WF3620</div></dd>

**Comment by o0shojo0o** [comment]
can you install the git version and test it?

**Comment by HReimann** [comment]
The Printername now visible but the Firmware Version still empty.
![image](https://user-images.githubusercontent.com/16271308/130649833-3303f92c-1e1f-4730-bb24-9b75d9344223.png)

It is also possible to include the waste Ink status?

**Comment by o0shojo0o** [comment]
I have changed something again in the detection of the firmware, can you still mla test the Git version?    
 Status of waste ink is not present in the ET series.

**Comment by HReimann** [comment]
Ok now it look's fine for me.. 
![image](https://user-images.githubusercontent.com/16271308/130662981-7b753945-4cf2-4218-ab2e-408df2800a8c.png)

thank your for the improvement...
