### ISSUE TITLE
Adapterumbenennung

### ISSUE THREAD

**Issue by Azathoth88** [iobroker-community-adapters/ioBroker.epson_ecotank_et_2750#9]
Ich habe ebenfalls erfolgreich den ET-4750 einbinden können. Aus meiner Sicht, macht es Sinn, dass der Adapter entsprechend umbenannt wird, damit eine breitere Usergruppe angesprochen wird. Vielleicht die Modellbezeichnung weglassen oder zumindest schon einmal 4750 ergänzen.

**Comment by o0shojo0o** [comment]
Hi @Azathoth88, 
recht hast Du, aber leider ist das nicht so einfach, da überall der Adapter schon mit der Bezeichnung unterwegs ist. 
Auch das npm Repo kann ich meines Wissens nicht so einfach umbenennen :(
